---
# tasks file for gitlab

- name: installing the required packages.
  package: name={{ item }} state=present
  with_items:
    - openssh-server
    - postfix
    - curl
    - openssl
    - tzdata

- name: include os specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: check if GitLab is installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_ctl

- name: check if GitLab postgresql data dir exists.
  stat: path={{gitlab_appdata_dir}}/postgresql/data
  register: gitlab_postgresql_data_dir

- name: download GitLab repo installation script.
  get_url:
    url: "{{ gitlab_repo_script_url }}"
    dest: /tmp/gitlab_repo_install.sh
    validate_certs: true
  when: not gitlab_ctl.stat.exists

- name: install GitLab repository.
  command: bash /tmp/gitlab_repo_install.sh
  when: not gitlab_ctl.stat.exists

- name: define the Gitlab package name and version to be installed.
  set_fact:
    gitlab_pkg_name: "{{ gitlab_edition }}{{ gitlab_pkg_separator }}{{ gitlab_version }}"
  when: gitlab_version != ''

- name: install GitLab
  package:
    name: "{{ gitlab_pkg_name | default('gitlab-ce') }}"
    state: present

- name: create GitLab SSL configuration folder if enabled.
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: 0700
  when: gitlab_self_signed_enabled

- name: create self-signed certificate if enabled.
  command: >
    openssl req -new -nodes -x509 -subj "{{ gitlab_create_self_signed_subject }}"
    -days 3650 -keyout {{ gitlab_ssl_certificate_key }} -out {{ gitlab_ssl_certificate }} -extensions v3_ca
    creates={{ gitlab_ssl_certificate }}
  when: gitlab_self_signed_enabled

- name: copy GitLab configuration file.
  template:
    src: "gitlab.rb.j2"
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
    backup: true

# begin special configuration.   
- name: create the gitlab-psql group
  group:
    name: gitlab-psql
    state: present

- name: create the gitlab-psql user
  user:
    name: gitlab-psql
    group: gitlab-psql
    state: present    

- name: create the new postgresql directory
  file:
    path: "{{ item }}"
    state: directory
    owner: gitlab-psql
    group: root
    mode: 0755    
    recurse: yes
  with_items:
    - "{{ gitlab_appdata_dir }}/postgresql"
  when: gitlab_appdata_enabled and not gitlab_postgresql_data_dir.stat.exists   
# end of special configuration
 
- name: reconfigure and start Gitlab
  shell: |
      gitlab-ctl reconfigure    


# systemctl service name:
# gitlab-runsvdir
