# execute platform specific installation step

- name: install the required sytem packages
  apt:
    update_cache: no
    name: "{{ item }}"
    state: present
  loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python-pip
 
- name: add docker repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# repo saved to /etc/apt# cd sources.list.d
- name: add the docker repository
  apt_repository:
    filename: docker.list
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: install docker
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: restart the service
  systemd:
    daemon_reload: yes
    state: restarted
    name: docker    

- name: make sure the service is running
  systemd:
    state: started
    enabled: yes
    name: docker      