---
# defaults file for gitlab

gitlab_edition: "gitlab-ce"
gitlab_version: '12.0.0'
gitlab_restart_when_fail: 'gitlab_restart.rc != 0'

###### GitLab Configuration
gitlab_external_url: "https://{{ansible_hostname}}/"
gitlab_git_data_dir: "/var/opt/gitlab/git-data"
gitlab_backup_path: "/var/opt/gitlab/backups"
gitlab_backup_s3: false
gitlab_backup_s3_region: 'us_west_1'
gitlab_backup_s3_directory: ''

gitlab_time_zone: "UTC"
gitlab_backup_keep_time: "604800"

gitlab_redirect_http_to_https: "true"
gitlab_ssl_certificate: "/etc/gitlab/ssl/gitlab.crt"
gitlab_ssl_certificate_key: "/etc/gitlab/ssl/gitlab.key"

gitlab_create_self_signed: "true"
gitlab_create_self_signed_subject: "/C=US/ST=California/L=Fremont/O=Ops/CN=gitlab"


##### LDAP Integration
gitlab_ldap_enabled: true
gitlab_ldap_host: "prodadq1.example.com"
gitlab_ldap_port: "389"
gitlab_ldap_uid: "sAMAccountName"
gitlab_ldap_method: "tls"
gitlab_ldap_bind_dn: "jenkinsad@ad.example.com"
gitlab_ldap_password: ""
gitlab_ldap_base: "CN=Users,DC=ad,DC=example,DC=com"
gitlab_ldap_group_base: "CN=Users,DC=ad,DC=example,DC=com"
gitlab_ldap_admin_group: ""

##### Omni Authentication
gitlab_omniauth_enabled: true
gitlab_google_app_id: ''
gitlab_google_app_secret: ''

##### SMTP Configuration
gitlab_smtp_enabled: true
# Gmail parameters

gitlab_smtp_address: 'smtp.gmail.com'
gitlab_smtp_port: 587
gitlab_smtp_user_name: ''
gitlab_smtp_password: ''
gitlab_smtp_domain: 'smtp.gmail.com'
gitlab_smtp_authentication: 'login'
gitlab_smtp_enable_starttls_auto: 'true'
gitlab_smtp_tls: 'false'
gitlab_smtp_openssl_verify_mode: 'peer' 
