---
# defaults file for gitlab

###### Recommended VM sizing
# 200-2000 users:
# CPU: 2-4 cores
# RAM: 8-16GB
# DATA: 500GB depending on repos size


###### Installation parameters
gitlab_edition: "gitlab-ce"
gitlab_version: '12.0.3-ce.0'
gitlab_restart_when_fail: 'gitlab_restart.rc != 0'

###### GitLab Configuration
gitlab_appdata_enabled: true
gitlab_appdata_dir:     "/appdata/gitlab"
gitlab_git_data_dir:    "/appdata/gitlab/git-data"
gitlab_backup_path:     "/appdata/gitlab/backups"

gitlab_backup_s3: false
gitlab_backup_s3_region: 'us_west_1'
gitlab_backup_s3_directory: ''

gitlab_time_zone: "UTC"
gitlab_backup_keep_time: "604800"

##### HTTPS
gitlab_https_enabled: false
gitlab_redirect_http_to_https: "true"
gitlab_ssl_certificate: "/etc/gitlab/ssl/gitlab.crt"
gitlab_ssl_certificate_key: "/etc/gitlab/ssl/gitlab.key"

gitlab_self_signed_enabled: false
gitlab_create_self_signed_subject: "/C=US/ST=California/L=Fremont/O=Ops/CN=gitlab"

##### LDAP Integration
#gitlab_rails['env'] = {
#    "http_proxy" => "https://USERNAME:PASSWORD@example.com:8080",
#    "https_proxy" => "https://USERNAME:PASSWORD@example.com:8080"
#}
gitlab_ldap_enabled: true
gitlab_ldap_host: "prodadq1.example.com"
gitlab_ldap_port: "389"
gitlab_ldap_uid: "sAMAccountName"
gitlab_ldap_method: "tls"
gitlab_ldap_bind_dn: "jenkinsad@ad.example.com"
gitlab_ldap_password: ""
gitlab_ldap_base: "CN=Users,DC=ad,DC=example,DC=com"
gitlab_ldap_group_base: "CN=Users,DC=ad,DC=example,DC=com"
gitlab_ldap_admin_group: ""

##### Omni Authentication
gitlab_omniauth_enabled: false
gitlab_google_app_id: ''
gitlab_google_app_secret: ''

##### SMTP Configuration
gitlab_smtp_enabled: false

# Gmail parameters
gitlab_smtp_address: 'smtp.gmail.com'
gitlab_smtp_port: 587
gitlab_smtp_user_name: ''
gitlab_smtp_password: ''
gitlab_smtp_domain: 'smtp.gmail.com'
gitlab_smtp_authentication: 'login'
gitlab_smtp_enable_starttls_auto: 'true'
gitlab_smtp_tls: 'false'
gitlab_smtp_openssl_verify_mode: 'peer' 


