---
# This playbook is used to install the Java SDK

- hosts: all
  become: true
  gather_facts: false

  pre_tasks:
  - name: install python (on Debian family) if not present
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    when: 1==1

# Install SDK roles
- hosts: all
  become: yes
  gather_facts: true

  vars:
    app_owner: vagrant
    app_group: vagrant
        
  pre_tasks:
    - name: create the appliction group if not present
      user:
        name: "{{ app_group }}"
        state: present

    - name: create the applicatin user if not present
      user:
        name: "{{ app_owner }}"
        group: "{{ app_group }}"
        state: present

    - name: create the build workspace directory
      file:
        path: /apps/build/jenkins
        state: directory
        recurse: yes
        owner: "{{app_owner}}"
        group: "{{app_owner}}"

  roles:
    - { role: common }
    - { role: gradle }